# versionはComposeファイルのバージョンでありDocker Compose自体のバージョンとは異なることに注意
version: '3.9'

volumes:
  mysql-volume:

services:
  # サービス名: PHP
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app

  # サービス名: Nginx
  web:
    # ビルドするDockerfileの指定
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # ローカル(PC)とDockerコンテナ間のポート番号の対応づけを設定{ローカル}:{Dockerコンテナ}
    ports:
      - 8080:80
    # コンテナ間の依存関係を設定(appはPHPアプリケーションのコンテナを指す)PHP->Nginxの順にコンテナを起動させる
    depends_on:
      - app
    # ローカルとDockerコンテナ間のディレクトリ・ファイル等のリソースを対応づける設定(ローカルのリソース:Dockerコンテナ内のリソース)
    volumes:
      - ./src/:/app

  # サービス名: MySQL
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # ローカルのポート番号(MySQLのデフォルトのポート番号は3306)
    ports:
      - 3306:3306
    # MySQLの環境変数
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql